# Generated by Django 2.1.5 on 2019-01-20 19:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ects', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(max_length=20)),
                ('groups', multiselectfield.db.fields.MultiSelectField(choices=[('G1M', 'G1M'), ('G2M', 'G2M'), ('G2M-B', 'G2M-B'), ('G3M', 'G3M'), ('G3M-B', 'G3M-B'), ('G3S1M', 'G3S1M'), ('G3S1M-B', 'G3S1M-B')], max_length=37)),
                ('schedules', multiselectfield.db.fields.MultiSelectField(choices=[('L9-10', 'L9-10'), ('L10-11', 'L10-11'), ('L11-12', 'L11-12'), ('L12-13', 'L12-13'), ('L13-14', 'L13-14'), ('L14-15', 'L14-15'), ('L15-16', 'L15-16'), ('L16-17', 'L16-17'), ('L17-18', 'L17-18'), ('L18-19', 'L18-19'), ('L19-20', 'L19-20'), ('L20-21', 'L20-21')], max_length=82)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScheduleGenerator.Semester')),
            ],
        ),
    ]
