# Generated by Django 2.1.5 on 2019-01-21 12:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='groups',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1M', '1M'), ('2M', '2M'), ('2M-B', '2M-B'), ('3M', '3M'), ('3M-B', '3M-B'), ('3S1M', '3S1M'), ('3S1M-B', '3S1M-B'), ('3S2M', '3S2M'), ('3S2M-B', '3S2M-B'), ('3S3T', '3S3T'), ('4S1M', '4S1M'), ('4S1M-B', '4S1M-B'), ('4S2M', '4S2M'), ('4S2M-B', '4S2M-B'), ('4S3T', '4S3T'), ('5S1M', '5S1M'), ('5S2M', '5S2M'), ('5S3T', '5S3T'), ('6S1M', '6S1M'), ('6S2M', '6S2M'), ('6S3T', '6S3T'), ('7S1T', '7S1T'), ('7S1T-B', '7S1T-B'), ('8S1T', '8S1T'), ('8S1T-B', '8S1T-B')], max_length=130),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schedules',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('L9-10', 'L9-10'), ('L10-11', 'L10-11'), ('L11-12', 'L11-12'), ('L12-13', 'L12-13'), ('L13-14', 'L13-14'), ('L14-15', 'L14-15'), ('L15-16', 'L15-16'), ('L16-17', 'L16-17'), ('L17-18', 'L17-18'), ('L18-19', 'L18-19'), ('L19-20', 'L19-20'), ('L20-21', 'L20-21'), ('M9-10', 'M9-10'), ('M10-11', 'M10-11'), ('M11-12', 'M11-12'), ('M12-13', 'M12-13'), ('M13-14', 'M13-14'), ('M14-15', 'M14-15'), ('M15-16', 'M15-16'), ('M16-17', 'M16-17'), ('M17-18', 'M17-18'), ('M18-19', 'M18-19'), ('M19-20', 'M19-20'), ('M20-21', 'M20-21'), ('MI9-10', 'MI9-10'), ('MI10-11', 'MI10-11'), ('MI11-12', 'MI11-12'), ('MI12-13', 'MI12-13'), ('MI13-14', 'MI13-14'), ('MI14-15', 'MI14-15'), ('MI15-16', 'MI15-16'), ('MI16-17', 'MI16-17'), ('MI17-18', 'MI17-18'), ('MI18-19', 'MI18-19'), ('MI19-20', 'MI19-20'), ('MI20-21', 'MI20-21'), ('J9-10', 'J9-10'), ('J10-11', 'J10-11'), ('J11-12', 'J11-12'), ('J12-13', 'J12-13'), ('J13-14', 'J13-14'), ('J14-15', 'J14-15'), ('J15-16', 'J15-16'), ('J16-17', 'J16-17'), ('J17-18', 'J17-18'), ('J18-19', 'J18-19'), ('J19-20', 'J19-20'), ('J20-21', 'J20-21'), ('V9-10', 'V9-10'), ('V10-11', 'V10-11'), ('V11-12', 'V11-12'), ('V12-13', 'V12-13'), ('V13-14', 'V13-14'), ('V14-15', 'V14-15'), ('V15-16', 'V15-16'), ('V16-17', 'V16-17'), ('V17-18', 'V17-18'), ('V18-19', 'V18-19'), ('V19-20', 'V19-20'), ('V20-21', 'V20-21')], max_length=426),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], max_length=15),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
