# Generated by Django 2.1.5 on 2019-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0002_auto_20190121_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='groups',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schedules',
            field=models.TextField(),
        ),
    ]
