# Generated by Django 2.1.5 on 2019-01-20 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0002_auto_20190120_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
