# Generated by Django 2.1.5 on 2019-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0003_auto_20190124_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Obligatory', 'Obligatory'), ('Optional', 'Optional')], max_length=10),
        ),
    ]
