# Generated by Django 2.1.5 on 2019-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0005_auto_20190126_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('Basica', 'Basica'), ('Obligatoria', 'Obligatoria'), ('Opcional', 'Opcional')], max_length=10),
        ),
    ]
