# Generated by Django 2.1.5 on 2019-01-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0005_auto_20190128_1624'),
        ('ScheduleGenerator', '0006_auto_20190126_2101'),
    ]

    operations = [
    ]
