# Generated by Django 2.1.5 on 2019-02-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0007_merge_20190128_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
