# Generated by Django 2.1.5 on 2019-02-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleGenerator', '0008_auto_20190201_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
